# Generated by Django 5.2.14 on 2026-09-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_content_post_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='memo',
        ),
    ]
